### ISSUE TITLE
Add profile name / pfp / clickable twitter tag to Gallery listing

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#21]
![image](https://user-images.githubusercontent.com/3628092/129458339-9ff3d872-6a52-40c6-bc2a-daf7446ff1e5.png)
Restyle the gallery so that these are shown under the thumbnails.

**Comment by nobooli** [comment]
Pfp and twitter tags have been added as links. Matthew is going through restyling them now

**Comment by nobooli** [comment]
Matthew has updated the gallery with pfp + clickable twitter tags 
![image](https://user-images.githubusercontent.com/85909428/129468196-088b7ca4-a218-40a6-b173-40c42dcc7a7f.png)
