### ISSUE TITLE
Bug: BGM is unstable

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#25]
I can't get it to play on page load most of the time

**Comment by nobooli** [comment]
Cause of issue is due to Audio object attempting to play before the user interacts with the page. Current solutions are to add an interactive element (preloader) to the page that will "trick" the user into acting so the BGM may be triggered and/or a manual play button.

**Comment by nobooli** [comment]
working bandaid currently is "BGM" label and manual play button.

Issue not fixed

**Comment by Type-kun** [comment]
Fixed through mandatory click on preloader
