### ISSUE TITLE
Add preloader

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#26]
Assets folder: https://drive.google.com/drive/folders/1wbn4CpmsOB8ZLwZjlbmdhfn4fTKEtLyw - look for "curtain" images

Rough idea: 
- while the page loads, left and right curtains are closed in the middle, with the shaded zain peeking through them.
- when the assets are loaded, shaded zain fades away, and the curtains slide left and right revealing the website contents.
- a BGM on/off switch icon plus volume control (optional) is displayed on preloader. Default is "on". 
- if the user chose "bgm on", start the music when the curtains start opening

Things to consider:
- Maybe require a click to open the curtains?
- Telegraph that the page is still loading. Maybe just add a box somewhere on the page saying "Loading..." and "ready. Click to start!"
- Show the preloader only for main page? Somewhat makes sense, but other pages will be jumpy without a preloader. Optionally, make a much simpler preloader for the cases when pages are opened through direct links.

**Comment by nobooli** [comment]
We do have the polpeller gif from the circus as an option to telegraph that the page is loading

**Comment by nobooli** [comment]
Curtain is live
