### ISSUE TITLE
Fix muting the BGM when going to soundboard and unmuting when going back

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#30]
Remember to preserve the state; only unmute if it was unmuted already. Also, hide the controls not to confuse the user.

**Comment by nobooli** [comment]
Navigating to Soundboard is muting the BGM and unmuting upon navigating away.

Once Soundboard is loaded, BGM slider is set to disabled so user can not override. Upon navigating away, slider is enabled again.
