### ISSUE TITLE
[Critical] Major soundboard slowdown after using the page for a while

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#33]
Likely a memory leak somewhere. Ask for help ASAP if we can't handle it ourselves.

**Comment by nobooli** [comment]
Unable to duplicate locally. Hypothesis is how github is hosting site. Looking for similar use cases while deploying

**Comment by nobooli** [comment]
Issue likely to have stemmed from previous repo's manipulation of slider via spawning 2 event handlers every time a sound clip was played. Fix deployed and tested using memory profiler in both browsers. Memory no longer jumps by 50 mb when spamming soundboard buttons
![image](https://user-images.githubusercontent.com/85909428/129460119-c7d000e3-2f8e-4b67-8625-e8149e27b6b4.png)
![image](https://user-images.githubusercontent.com/85909428/129460168-518ff994-d4be-42ca-8876-cb5561811810.png)
