### ISSUE TITLE
BGM controller slider resets to muted when moving between pages

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#34]
The BGM itself doesn't stop.

**Comment by nobooli** [comment]
Retesting thoroughly

**Comment by nobooli** [comment]
BGM is currently preserving settings when navigating between the following pages
- Main
- Gallery
- Messages
- Quiz
    - QuizEN
    - QuizJP
    - QuizZH
    
BGM will be muted and BGM slider disabled upon navigating to the Soundboard page regardless of current state.

Upon navigation back to the previously mentioned pages, BGM slider will become enabled again and BGM will resume previous settings pre navigation to Soundboard
