### ISSUE TITLE
Stop soundboard sounds playing when moving away from the page

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#35]
Currently the sound continues to play

**Comment by nobooli** [comment]
Because Vue is a Single page application, the Audio object does not get destroyed during navigation. Solution would be to to detect navigation and pause the object inside the Soundboard's model before navigation starts/occurs.

**Comment by nobooli** [comment]
This has been resolved by putting in a route guard to trigger before leaving the page
