### ISSUE TITLE
[wait] Reposition the marquee on the main page

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#43]
If we are keeping the marquee, stylize it further by putting it above the tent entrance and making it smaller. Eats up too much precious vertical space otherwise.
![image](https://user-images.githubusercontent.com/3628092/129460793-3667b6a6-e060-4d94-8bde-7cc8860ab4d2.png)

**Comment by Type-kun** [comment]
This implies sticking the other assets to the top and moving the tent closer vertically to the title, of course.
![image](https://user-images.githubusercontent.com/3628092/129460966-9078b555-dee4-49e4-85dd-78a81d9b9f70.png)

**Comment by Type-kun** [comment]
Let's leave the marquee at the bottom of the page for now

**Comment by matthewyingtao** [comment]
good to close?
