### ISSUE TITLE
Missing flags assets on the main page

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#46]
https://drive.google.com/file/d/15YzI5eDF_BhHMMDRYfaAMeI49PzKO7Q1/view?usp=sharing

This image was supposed to stick to the top navigation bar, overlaying the top of the page, like flags under the ceiling.

![image](https://user-images.githubusercontent.com/3628092/129461155-70d392a8-625b-4ea1-ad8f-190c5ebbd5bf.png)

**Comment by matthewyingtao** [comment]
added
