### ISSUE TITLE
Fix main page banner padding

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#48]
Currently like this:
![image](https://user-images.githubusercontent.com/3628092/129462154-9d573b5c-5042-4161-9713-01e9e9d395b0.png)
Should be like this:
![image](https://user-images.githubusercontent.com/3628092/129460966-9078b555-dee4-49e4-85dd-78a81d9b9f70.png)

**Comment by nobooli** [comment]
Matthew has updated the banner to always stick to the top
