### ISSUE TITLE
Repurpose "force play BGM" button as "play/pause BGM" button

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#55]
This kind of behavior is more obvious for the user.

**Comment by nobooli** [comment]
Additionally, Play/Pause button toggle is broken in soundboard. Clicking the pause button will not change the icon to Play button

**Comment by nobooli** [comment]
The force play BGM button is now operating as Play/Pause.

The Play/Pause/Reply button for the Soundboard has also been fixed.
