### ISSUE TITLE
Reduce the gap between banner and the circus tent

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#56]
![image](https://user-images.githubusercontent.com/3628092/129466603-a0714e5d-4e47-47cf-a66c-5a32c2f602f9.png)
The flag might as well be almost grazing the sign

**Comment by nobooli** [comment]
![image](https://user-images.githubusercontent.com/85909428/129471689-affa59c7-3cc3-4e73-90ce-a22267dd8b07.png)
Moved tent as close as possible without covering the bottom kira kira
