### ISSUE TITLE
[Bug] Messages jump around while loading

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#65]
![image](https://user-images.githubusercontent.com/3628092/129469227-ab553668-1b77-4724-b572-bb4ae5e62633.png)

Results in something like this occasionally

**Comment by Type-kun** [comment]
![image](https://user-images.githubusercontent.com/3628092/129469244-e82b757c-7a54-4f84-9a3d-37bf481fd4da.png)
Everything seems fine after the page loads fully. Maybe lazy loading got broken on messages?

**Comment by RayWarthog** [comment]
This should be because animate-on-scroll calculates the layout before the images are loaded.

Should be fixed with https://github.com/nobooli/POLton/pull/69, refreshing AOS once the images are loaded.
