### ISSUE TITLE
Restyle the quiz language selector

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#66]
![image](https://user-images.githubusercontent.com/3628092/129470441-360917bf-dff7-4e3b-880c-4b0df1030bd7.png)

- Drop the text
- Make buttons larger and stack vertically (let them fill the screen on mobile)
- Leave space on the left side of the button for potential icons (either flags or zains)

**Comment by nobooli** [comment]
Text removed.

Buttons changed to vertical stacking and beefed up in size with some space left for additions.

![image](https://user-images.githubusercontent.com/85909428/129471598-71d8f396-8680-4d15-94ba-e4fb60c1a850.png)
