### ISSUE TITLE
[Bug] fetching the result from exec link is currently broken

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#67]
![image](https://user-images.githubusercontent.com/3628092/129470541-068026b9-a384-4645-8f1f-2593961be488.png)

tries to open exec(uuid) now, should be exec?id=(uuid)

**Comment by nobooli** [comment]
resolved in commit d120e62, deploying now

**Comment by nobooli** [comment]
Apologies, I've rectified this in 8c1ded4
