### ISSUE TITLE
Add the text plaques below Zains on main page

### ISSUE THREAD

**Issue by Type-kun** [nobooli/POLton#70]
![image](https://user-images.githubusercontent.com/3628092/129470844-fc82da74-b0d7-4613-8a12-cfaa37a5b223.png)
Place under each zain; write a short description in EN and JP depending on language; possibly rotate.

[nameplates.zip](https://github.com/nobooli/POLton/files/6987721/nameplates.zip)

**Comment by nobooli** [comment]
Mobile
![image](https://user-images.githubusercontent.com/85909428/129475331-136f0904-178c-4015-bbac-de6193e78554.png)

potato
![image](https://user-images.githubusercontent.com/85909428/129475364-389928c7-ea21-405d-960c-b83e145899fa.png)

beef
![image](https://user-images.githubusercontent.com/85909428/129475417-8b193efd-a370-4b67-bf21-cc5a8c515b1a.png)
